"use strict";
require("./style.css");
const { Component } = require("./Component");
console.log("webpack");
const resultSumTwoNumber = 5 + 3;
console.log(resultSumTwoNumber);
console.log("webpack 2");
console.log("qwerty");
const comp1 = new Component();
comp1.render();
